### ISSUE TITLE
Behavior of matrix number registers

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/pspautotests#190]
https://github.com/hrydgard/ppsspp/pull/9136
https://github.com/hrydgard/ppsspp/issues/8110

It may be these wrap at 0x1F, 0xFF, 0xFFFF, 0xFFFFFF, or not wrap at all.  This likely impacts all the matrix number registers.

-[Unknown]

**Comment by hrydgard** [comment]
It may even be that if you overflow one matrix count register, another matrix starts changing if you write to that matrix data register, if they are somehow consecutive in a hidden way. Or not. Hardware tests indeed required to be sure.

**Comment by unknownbrackets** [comment]
See later comments in https://github.com/hrydgard/ppsspp/pull/9136 for some notes.

Did a bit more testing here.  Used `sceGeSaveContext()` to compare matrix data values.

First, the bone matrix:
 * Setting number to 0x2AFFFFFF reads back as 0x2A00007F with or without data commands.
 * As far as I can tell, all bits outside the first 7 (i.e. <= 127) are entirely ignored and the register doesn't even store them.
 * Setting explicitly to number 95, then sending one data, left the reg returning 96.
 * Setting bone matrix data at 96 changed the world matrix values, then view and proj, through proj 7.
 * Even setting 127 explicitly, the value wraps to 0 and sets the bone matrix values again (it's not possible to affect past proj 7.)

For all other matrices (world, view, proj, texgen):
 * For all four, the number reads back only the low 4 bits (not 7 like bone), with or without data commands.
 * The value wraps after 15 (even if matrix size is 12.)
 * For world and view, data for 12-15 affect the next matrix, considering this order: bone, world, view, proj, texgen.
 * Proj obviously cannot overflow given these rules, and doesn't no matter how many values are sent.
 * Texgen overflow seems to have no affect on any other values, at least saved in the context struct.

So it does seem to be as you suspected.

-[Unknown]

**Comment by hrydgard** [comment]
That's interesting! I completely forgot that suspicion, heh.

**Comment by unknownbrackets** [comment]
Just wanted to note, ran a quick test of all but the action registers (i.e. not loadclut, prim, jump, etc.) and only the matrix registers have this behavior.  Writing to any of the matrix data regs reads back as 0, and num regs work as I described.  The other regs (again, didn't check action regs) retain all set bits, even if they have no function.

-[Unknown]

**Comment by unknownbrackets** [comment]
Did a bit more testing to try to figure out why this logic doesn't handle the case in https://github.com/hrydgard/ppsspp/pull/9136.

It ends up seemingly more complicated:
 * There's, as far as I can observe so far, two sets of values for each matrix.  The set visible to the CPU, and the ones the GPU is actually using.
 * The GPU visible values do not wrap, at all (at least not for 512 entries.)  And they also do not bleed between matrices.
 * The CPU visible values work as I've described above, bleeding between and wrapping.
 * If the number register is written to, the GPU visible number resets to the masked value (i.e. 0xF0 is the same as 0, and enables GPU writes.)  Note that 0x0C on view still means no GPU visible writes.
 * If the list was enqueued using a context for saving, or otherwise sceGeSaveContext is called, it reads the CPU visible values.  But when the context is restored, those values are written to the GPU visible values.  So the CPU behavior is still relevant to the GPU.
 * In general it seems like the CPU visible value behavior is some kind of (hardware?) bug.  I don't think they're actually cached in software, I don't think the firmware code is searching lists for these commands.

-[Unknown]

**Comment by hrydgard** [comment]
Wow! Wonder what the explanation for this is. 

Maybe they designed the matrix registers as write-only in the GPU core, but then realized it was necessary to be able to read them back, but didn't want to change the core at that point, so they added a little bit of (buggy) storage to the GPU command processor to compensate?

**Comment by hrydgard** [comment]
I think we can call this case closed? Very nice work!

**Comment by unknownbrackets** [comment]
Yes, although I haven't made a simple test to illustrate this exactly.  We do see it in gpu/ge/get mostly, but not the use of the matrix.  I suppose we can still close this.

-[Unknown]
